# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
    ]
